### ISSUE TITLE
Remove use of function constructor

### ISSUE THREAD

**Issue by billyjanitsch** [kensho-technologies/orama#66]
Generally it's not good practice to call the `Function` constructor. Like `eval`, it's a fragile operation with many associated security vulnerabilities, and there is usually a better solution.

https://github.com/kensho-technologies/orama/blob/520d5b47be9156e0e56de703507d4fbf63d81dc5/src/dataHelpers.js#L15

We should figure out why we're calling the constructor here, and come up with a better solution.

**Comment by nabeel-** [comment]
It looks like the use of `new Function` is meant to take an expression as a string and evaluating it given a context, for example: `"a + b"` with the context `{a: 1, b: 2}` and expecting the outputted result to be `3`. This functionality is used to transform an object of expressions into the evaluated results.

It's currently not used anywhere and the commit that introduces the code does not point to any use-case so the best path forward may be to remove it. (Similar to how the `imageRenderer` was handled https://github.com/kensho-technologies/orama/issues/50)

**Comment by billyjanitsch** [comment]
Oh, you're right, the entire dataHelpers.js file is totally unused. It's not even [re-exported](https://github.com/kensho-technologies/orama/blob/5945318dedf87725a3a4d9524efe9612d6ae31e7/src/index.js), so removing it is not a breaking change.

Thanks for investigating, sorry this was no fun.
