### ISSUE TITLE
Enable onEvent bindings?

### ISSUE THREAD

**Issue by georgesboris** [kensho-technologies/orama#7]
I wish I would be able to take an action when the user hovers or clicks a data point.
However I did not found anything in the docs on how to do this. Is this available?
Is there any design issues on enabling this?

My use case is this:
I have an area chart that I wish I would display additional information when the user hovers a data point. I understand there is the tooltip component but the information would be better displayed in a larger and fixed container. (The container will display the details of the last hovered/clicked even when the user leaves the chart.)

And congratulations again on this library Luis. I was using chart.js since I had no available time to study d3.js  properly. But I quickly found myself trying to compose different chart types and with this library this is a complete breeze. Thanks!

**Comment by luiscarli** [comment]
Hi Georges!

Orama has an event callback, but I have not documented it yet.

Here's a quick example that can get you going before I update the docs, most of the keys on the object returned by the callback are self-explanatory:
```jsx
<or.Chart onUpdate={data => {
  if (data.action == "mouseMove" && data.hoverData) {
    // data.hoverData will be the closest data point on the area that you're hovering
    // if you have multiple layers you will need more logic for checking what are you hovering
 }
}}>
  <or.Areas/>
</or.Chart>
```

**Comment by georgesboris** [comment]
That works perfectly! Thanks.
