### ISSUE TITLE
Tooltip offset from position

### ISSUE THREAD

**Issue by georgesboris** [kensho-technologies/orama#8]
I've encountered a problem but I'm still trying to reproduce it outside my app.
My chart is inside several containers with fixed > absolute positions.
It's tooltip is being offset by the chart's relative parent 'left' position.
I tried studying the TooltipWrapper component but couldn't figure the problem that easily.
I'll continue trying to reproduce the problem in codesandbox.io and place the link here when I'm done.

**Comment by luiscarli** [comment]
The TooltipWrapper use `position: fixed;`; with the `top` and `left` styles set to the mouse `x` and `y`. But maybe there's a combination of css containers that can that setup unreliable. Let me know if you manage to reproduce the problem!

**Comment by georgesboris** [comment]
Just so you know that something is indeed going on.

<img width="331" alt="captura de tela 2017-06-13 as 4 13 38 pm" src="https://user-images.githubusercontent.com/3660797/27100100-4f58ea7c-5053-11e7-9ff9-b663e19fa9e3.png">

I'm checking it out.

**Comment by nabeel-** [comment]
FWIW, `position: fixed` will use a `transformed` ancestor as the viewport instead of the browser window. As of this comment it is intended behavior and the corresponding bug report in chromium has a `Won'tFix` status.

Source: https://bugs.chromium.org/p/chromium/issues/detail?id=20574
